export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const LOAD_PROJECT_TYPES = 'LOAD_PROJECT_TYPES';
export const LOAD_TARGET_DEVICES = 'LOAD_TARGET_DEVICES';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const UPDATE_MAIN_TITLE_SUCCESSS = 'UPDATE_MAIN_TITLE_SUCCESS';
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
