export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const LOAD_PROJECT_TYPES = 'LOAD_PROJECT_TYPES';
export const LOAD_TARGET_DEVICES = 'LOAD_TARGET_DEVICES';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
